### ISSUE TITLE
[HST-005] CSSのリファクタリング

### ISSUE THREAD

**Issue by takapi327** [takapi327/html-scss-training#10]
# Refactoring
## 内容
- extendsからmixinに変更
  - mixin専用のファイルを作成
### mixin
@mixinは、@mixin hoge(){}という記述でスタイルを定義して、別の場所でそのスタイルを使い回せる機能であり、さらに「引数」が使えるという大きなメリットがある。

```css
@mixin text {
//予め共通項をつくっておく
font-size: 14px;
font-weight: 400;
}
.text-red {
@include text;
color: red;
}

.text-blue {
@include text;
color: blue;
}

.text-green {
@include text;
color: green;
}
```
cssに展開すると下記のようになる。
予め定義したものを共通化して使っているのがわかります。

```css
.text-red {
font-size: 14px;
font-weight: 400;
color: red
}

.text-blue {
font-size: 14px;
font-weight: 400;
color: blue
}

.text-green {
font-size: 14px;
font-weight: 400;
color: green
}
```
### extend
@extendは一言で言うと「継承」。
@extendは手軽に使えて、スタイルがグルーピングされてコードが短くなるという点は良いが、スタイルを定義した元のクラスは無駄に記述されてしまうというデメリットがある。
```css
%text {
 font-size: 14px;
 font-weight: 400;
}

.text-red {
 @extend %text;
 color: red;
}

.text-blue {
 @extend %text;
 color: blue;
}

.text-green {
 @extend %text;
 color: green;
}
```
cssに展開すると下記のようになる。
共通化しているというにはなんか違う感じがする。
```css
.text-red, .text-blue, .text-green {
font-size: 14px;
font-weight: 400
}

.text-red {
color: red
}

.text-blue {
color: blue
}

.text-green {
color: green
}
```
## 参考文献
[Sassにおけるextendとincludeの違い](https://hajipion.com/1002.html)
[Sassの「@mixinと@extendの違い」と使い分け](https://stand-4u.com/css/sass/mixin-extend.html)
