### ISSUE TITLE
[HST-002] Headerの作成

### ISSUE THREAD

**Issue by takapi327** [takapi327/html-scss-training#3]
# Headerの作成
## 目次
- [内容]()
- [学び]()
  - [BEM記法]()
- [参考文献]()
  - [CSS記法]()

## 内容
- HTMLをBEM記法に修正
  - headerBlockを作成
  - headerBlockのElementを作成
- BEN記法に沿ったSCSSの作成
  - 画像の追加
  - 各要素のサイズを調整
  - 表示位置の変更、フォントサイズの変更

### BEM記法
Block Element Modifierの略で,
Block => でかい括り(親クラス)
Element => でかい括りの中にいる要素(子クラス)
Modifier => 上記2つの変化球(JSなどの動き？)
の3つに分けて考えていくことでCSSを設計･命名していく手法.
#### 記述のルール
SCSSファイルは1blockにつき1ファイル作成する。逆に言うと1ファイル内に複数のblockが定義されているのは違反になるらしい。
ファイル名は block名.scss となる。
>CSSは全ての名前がグローバルなため, 命名が重複するとメンテナンス性が著しく低下するのが弱点であるが, BEMは命名規則を厳しく縛ることによってこの弱点を克服しており, element名はいくら重複しても問題ない.
ただし, block名が重複してしまうとせっかく克服したものが台無しになってしまうため絶対に避けなければならない.
1ファイルにつき1blockしか定義せずファイル名をblock名にする規則を守ってさえいれば, block名が重複する心配が無い.

このような理由からルールが決められている。
ただ記事によっては、Blockの中にBlockを作成てもいいみたい。ここは各々のプロジェクトによるのかな。
### element
またelement内にさらにelementをネストして定義してはいけないらしい。
```scss
.article-list {
  width: 100%;

  &__article-title {
    font-size: 20px;

    &__article-subtitle {
      font-size: 16px;
    }
  }
}
```
今までネストしまくっていたので驚き。
そもそもBEMを正しく理解していなかったので、自分の今までのコードがめちゃくちゃだったと思った。
HTMLとSCSSの分離を目指すため、HTMLの構造がどうであれ、 elementがblock以外を親に持つのを避け、 以下のように書けば正しい記述になる。
```scss
.article-list {
  width: 100%;

  &__article-title {
    font-size: 20px;
  }

  &__article-subtitle {
    font-size: 16px;
  }
}
```
#### modifier
modifierはネストと親セレクタ名参照を使って定義するので下記のような実装になる。
```scss
.article-list {
  width: 100%;

  &__article-title {
    font-size: 20px;

    &--red {
      // この中身がどうなるかは後述. もちろんこのままでは何も機能しない.
    }
  }

  &__article-subtitle {
    font-size: 16px;
  }
}
```
上記は色を赤色に帰るだけの実装でその他のSCSSは親クラスの定義と同じになっている。この場合何度も同じSCSSの記述をしてしまう可能性があるので、`@extend`を使い統一できるものは予め定義しておいて変更したいSCSSの内容だけを書くようにする。
```scss
.article-list {
  width: 100%;

  %__article-title {
    font-size: 20px;
  }

  &__article-title {
    @extend %__article-title;

    &--red {
      @extend %__article-title;
      color: red; 
    }
  }

  &__article-subtitle {
    font-size: 16px;
  }
}
```
これで赤以外にも違う色のものを作りたくなっても同じように色だけを変えてあげれば簡単に実装を行える。

## 参考文献
[[HTML/SCSS]BEM設計をワイヤーフレームを使って解説してみる](https://qiita.com/mame_hashbill/items/c5b09461d7acfce047fa)
[CSSプロパティ記述順序](https://qiita.com/mgn/items/6154ccd2e23b2e65c769)
[SEO対策として最低限押さえておきたいHTML/HTML5マークアップの大事な6つのポイント](https://creive.me/archives/8814/)
[一番詳しいCSS設計規則BEMのマニュアル](https://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1)

### CSS記法
[background-position](https://developer.mozilla.org/ja/docs/Web/CSS/background-position)
[CSS の background-size での cover、contain、auto の違い](https://www.keicode.com/script/css-background-size.php)
[background-repeat](https://developer.mozilla.org/ja/docs/Web/CSS/background-repeat)
[background-attachment](https://developer.mozilla.org/ja/docs/Web/CSS/background-attachment)
[CSS Flexbox](https://www.webcreatorbox.com/tech/css-flexbox-cheat-sheet)
